### ISSUE TITLE
Top nav links do not work

### ISSUE THREAD

**Issue by j08lue** [EOEPCA/docroot#2]
Steps to reproduce:

1. Go to https://eoepca.readthedocs.io/en/latest/
2. Click on one of the top nav links - currently System Architecture or Deployment Guide
   
   ![image](https://github.com/EOEPCA/docroot/assets/3404817/ab783aca-36d4-472e-8a98-36b6c2212b48)

3. Note that you get sent to https://eoepca.readthedocs.io/en/latest/projects/architecture/ (broken) - should be https://eoepca.readthedocs.io/projects/architecture/en/latest/ (working)

   ![image](https://github.com/EOEPCA/docroot/assets/3404817/cbabb83a-b834-4c5f-895d-4562f2c85376)

## Acceptance criteria

- [ ] Top nav links work

**Comment by j08lue** [comment]
Perhaps `/projects/architecture/`(note leading slash for root) works better?

https://github.com/EOEPCA/docroot/blob/f5857f0df776b38719a2ecd1947668beb41baa46/mkdocs.yml#L25-L26

**Comment by rconway** [comment]
@j08lue Thanks for the tip - and spotting the issue
